Publish am-v3.0-psd01
oslc-op/oslc-specs pull request #420
Opened 2020-08-25 20:33 UTC by jamsden

2020-08-25 21:37 UTC, berezovskyi commented on specs/am/architecture-management-shapes.ttl
>    dcterms:isPartOf <https://oslc-op.github.io/oslc-specs/specs/am/architecture-management-spec.html> ;
dcterms:source and dcterms:isPartOf need to be changed to point to their future locations on open-services. See https://github.com/oslc-op/oslc-specs/pull/407/files

2020-08-25 21:37 UTC, berezovskyi requested changes
Nice, one more spec to become a PSD. See the comment inside and please add a changelog entry for the PSD, also see https://github.com/oslc-op/oslc-specs/pull/407/files for an example.

2020-08-26 12:36 UTC, jamsden commented
We have an agreement with Chet that the change history appendix is no longer needed - we use GitHub for that. This was a hold over from TC specs that didn't use version management. I left the old ones in as part of the transition from the TC to OP, but I don't think its worth maintaining these tables.

2020-08-26 13:19 UTC, berezovskyi commented on specs/am/architecture-management-shapes.ttl
>    dcterms:source <https://github.com/oslc-op/oslc-specs/blob/master/specs/am/architecture-management-shapes.ttl> ;
also needs to point to OASIS

2020-08-26 13:22 UTC, berezovskyi commented on specs/am/architecture-management-spec.html
> -          <td>08/22/2017</td>
then let's remove the table altogether to avoid confusion

2020-08-26 13:23 UTC, berezovskyi commented on specs/am/architecture-management-spec.html
> -          <td>08/22/2017</td>
and the enclosing section, ofc

2020-08-26 14:00 UTC, jamsden commented
Unfortunately we have not done that uniformly. Let's ignore this for the PSD and address it in the next revision. If we're going to do this, we need to 1) determine if its essential, and 2) apply it uniformly. I want us to focus on delivery and only do essential changes in these documents going forward.

2020-08-26 14:01 UTC, berezovskyi commented
Okay please fix the dcterms source and it’s ready for submission

2020-08-26 14:01 UTC, berezovskyi commented
Okay please fix the dcterms source and it’s ready for submission

2020-08-26 15:31 UTC, berezovskyi approved these changes
Please prepare a ZIP and I will file start the process. Just recalled because it's just a a PSD I don't need to wait on Chet.

2020-08-26 15:48 UTC, merged