Jra auto psd01
oslc-op/oslc-specs pull request #447
Opened 2020-11-03 19:45 UTC by jamsden

Getting the Automation spec so that it can be published as a PSD in order to be referenced.

2020-11-03 19:54 UTC, jamsden commented
@ndjc I'm getting a ReSpec error that the conformance section is missing (and indeed it is) in automation-spec.html. But the section with id="conformance" is there. I can't find anything wrong. Can you take a look?

2020-11-04 12:03 UTC, berezovskyi requested changes

2020-11-04 12:03 UTC, berezovskyi commented on specs/auto/automation-shapes.html
> +        OSLC Automation Version 2.1 Part 2: Vocabulary defines the OSLC Automation RDF vocabulary terms and resources.
Part 3

2020-11-04 12:03 UTC, berezovskyi commented on specs/auto/automation-shapes.html
> +      <section id="Resource_Dialog">
I think the id has to be DialogShape for proper HTML conneg link destinations

2020-11-05 17:25 UTC, ndjc commented
>  I'm getting a ReSpec error that the conformance section is missing (and indeed it is) in automation-spec.html. But the section with id="conformance" is there. I can't find anything wrong. Can you take a look?

@jamsden the problem is that you have specified `noConformanceTable = true` in the configuration section, but you have not specified your own conformance section **text**. You must either use the auto-generated table, or provide your own text. For example, in your Core file `core-shapes.ttl` you have `noConformanceTable = true` but with the following explicit conformance section with content:

>     <section id="conformance">
>       <h2>Conformance</h2>
>       <p>OSLC servers MUST follow the constraints defined here where required, and with the meanings defined here.</p>
>       <p>OSLC servers MAY provide additional constraints for specific purposes.</p>
>     </section>

2020-11-06 14:03 UTC, ndjc approved these changes
Changes to conformance table look good.
I see at least two missing vocabulary terms:

1.  The enum value `oslc_auto:passed`. This is a verdict, like `error`, `fail`, `unavailable`, or `warning`. All those are in the vocabulary, but `passed` is missing.
2. The property predicate `oslc_auto:progress`. This is one of the new terms needed by OSLC Configuration Management. I'll send a draft property definition separately.

I say at least two, because there are several ShapeChecker errors. While most of these are missing or incorrect parts of otherwise good property definitions, there are some that point to inconsistencies in the way parameters are defined. For example, the shapes use `:inputParameter` and `:outputParameter`, but the vocabulary defined `:additionalParameter`.

While all these issues need to be fixed, I'm approving the PR so that we can have a first version of the draft in the master branch.

2020-11-06 14:13 UTC, ndjc commented
Here's an OSLC property definition for the oslc_auto:progress property:

>         [
>             #progress
>             a                        oslc:Property ;
>             oslc:name                "progress" ;
>             oslc:propertyDefinition  oslc_auto:progress ;
>             oslc:occurs              oslc:Zero-or-one ;
>             oslc:readOnly            true ;
>             oslc:valueType           xsd:integer ;
>             dcterms:description      "The percentage (0-100) of completion, if known."^^rdf:XMLLiteral
>         ] ,

Here's a possible vocabulary entry:

>        <http://open-services.net/ns/auto#progress>
>               a                 rdf:Property ;
>               rdfs:comment      "A percentage (0-100) of completion." ;
>               rdfs:isDefinedBy  <http://open-services.net/ns/auto#> ;
>               rdfs:label        "progress"  .

2020-11-09 22:03 UTC, berezovskyi approved these changes

2020-11-09 22:29 UTC, berezovskyi commented
![image](https://user-images.githubusercontent.com/64734/98604096-64dc1e80-22e3-11eb-856f-0166e8fbe0bf.png)

@jamsden press "update the base branch" to solve the lint build issues before merge, I fixed them in master

2020-12-04 16:12 UTC, merged